### ISSUE TITLE
Server error when trying to permanently delete account

### ISSUE THREAD

**Issue by Plonq** [bitwarden/web#35]
Trying to delete account because I can't bulk delete imported logins, but get a server error.

Chrome Version 55.0.2883.87 m (64-bit)
Windows 10

![chrome_2017-01-16_10-07-45](https://cloud.githubusercontent.com/assets/7709415/21967045/c2942352-dbd3-11e6-99f6-212eca4b8a76.png)
![chrome_2017-01-16_10-08-19](https://cloud.githubusercontent.com/assets/7709415/21967046/c43338f6-dbd3-11e6-86f5-744938b1685d.png)

**Comment by kspearrin** [comment]
I put a possible fix in next release for this. How many logins are in your vault? In the meantime, feel free to email me using the contact form on the website and I can do this for you manually.

**Comment by Plonq** [comment]
My vault has 789 logins. Happy to wait until next release as at the moment I'm not using bitwarden as my primary password manager.

(Had import issue (not a bitwarden issue) which created heaps of blank logins that would take ages to delete one by one).

**Comment by kspearrin** [comment]
@Plonq  Give it a try now please.

**Comment by Plonq** [comment]
Fixed. Took a little over a minute (estimated).

**Comment by kspearrin** [comment]
I still see a timeout error in the server logs. Did it initially or something?

**Comment by Plonq** [comment]
>Did it initially or something?

What do you mean?

I just created a new account with the same details successfully, and it has no logins as expected.

**Comment by kspearrin** [comment]
Was a typo. Corrected. I meant Did it **fail** initially or something.

**Comment by Plonq** [comment]
Nope, worked first time I tried.

**Comment by kspearrin** [comment]
Nevermind. The error was for something else. Thanks!
