### ISSUE TITLE
Lastpass Import Issues

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/web#7]
I have had a few reports from users who are having issues importing their exports from Lastpass. I have not been able to reproduce the issue and there are many others who have imported their sites from Lastpass without issue (including those with thousands of sites). Obviously I cannot just ask those users to just send me their export file so that I can debug it. More investigation is needed to try to reproduce this issue so that all users can import from Lastpass.

**Comment by stylersnico** [comment]
The export file from lastpass isn't working.

But if you open the .html file and copy / paste the text in a file and import it into bitwarden it works 👍

**Comment by amitkparekh** [comment]
I'm also having issues with the Lastpass import.

For me, I noticed that I had one password was (for some reason) 206 characters long and looked like a random string. So I converted the plain text to csv in Excel, and this time removed that one line, and the import worked.

**Comment by zefareu** [comment]
Not working for me. I've tried the suggestions above -- created a new csv file, copy/pastes the data into it, still errors out on import.

**Comment by bcallaars** [comment]
For me it's mostly the secure notes that are bodging up the CSV, for example having a SSH key in there will definitely kill it.

**Comment by zefareu** [comment]
Well, I just tried again, and it worked. I'm pretty sure I did everything exactly the same, but I'm good now!

**Comment by bcallaars** [comment]
Right, what I did to solve it was this: 

- Copy and paste the export from LastPass (don't save the file as the idiots output HTML for some reason)
- Import file into Excel, LibreOffice, whatever
- Clean it up
- Export it as a CSV file
- Import into Bitwarden

**Comment by kspearrin** [comment]
Any of you guys that have had this problem, any chance that you could debug it using your file and see what's going on?

**Comment by kspearrin** [comment]
Or post a scrubbed file that can reproduce the issue?

**Comment by stylersnico** [comment]
@kspearrin Already closed and deleted my keepass account, sorry :/

What is the business model of bitwarden anyway? Can we make a donation or something like that?

**Comment by KarimGeiger** [comment]
I'm having a similar problem. Removing long URLs didn't work for me, but I noticed that my notes contain some plaintext having a comma (the delimiter) in it. Maybe that's whats causing the error.

**Comment by bcallaars** [comment]
It's definitely the notes being the problem, LastPass simply exports the notes including any breaking characters. I think the best solution is to clean up the file first by making sure that at least every line starts with`http` at least. I'll see if I can conjure up a scrubbed file with the same issue.

**Comment by kspearrin** [comment]
I have released v1.1.0 with some fixes to accommodate the folks who have been trying to upload the HTML version of the export: https://github.com/bitwarden/web/releases/tag/v1.1.0

**Comment by kspearrin** [comment]
@KarimGeiger That shouldn't matter as long as the entire thing is wrapped in quotes.

**Comment by kspearrin** [comment]
Ok, I think we've finally figured this out. I don't think it has anything to do with the secure note itself. I received an email from a user that pointed out that his export from LastPass had a few entries with empty passwords (I'm sure many secure notes do not have passwords). After removing those entries he was able to import successfully. I'll work on an update for this tonight and hopefully get it pushed out tomorrow.

In the meantime if you want this to work, just fix the empty password fields in your CSV file (open it with a spreadsheet program like Excel or something).

Let me know if anyone can test this and if it solved your problem.

**Comment by kspearrin** [comment]
I have released v1.1.1 with more fixes for everyone. Please let me know if anyone is still having issues after this release. Also, please report back and let me know if this resolved the issue for you as well.

**Comment by KarimGeiger** [comment]
Awesome, works like a charm now without adjusting the file at all (even HTML import). Thanks for the quick fix.

**Comment by kspearrin** [comment]
More fixes pushed out for lastpass imports with v1.2.1: https://github.com/bitwarden/web/releases/tag/v1.2.1

**Comment by kspearrin** [comment]
I believe we can declare this resolved. I have not received a report in quite some time.

**Comment by NormaJeanBaker** [comment]
Hello,
for me it isn't solved. I still cannot import from LastPass. Neither with importing the generated csv-file directly nor with the copy-and-paste-method.
I also tried removing all entries with secure notes and any wifi-access-entries (as those wifi things were formatted as some kind of xml). To no avail.
The error message I keep getting is a complaint about the password field apparently being too long somewhere (sorry, can't copy the exact message from the screen).

**Comment by kspearrin** [comment]
@NormaJeanBaker  The error message will give you a row number of the offending entry. You can then locate the row in Excel and correct the password.

**Comment by NormaJeanBaker** [comment]
I looked at the error message, which in fact gives a number.
The row in question looks completely harmless to me. In fact it is this row:
https://www.paypal.com/de/cgi-bin/webscr?cmd=_login-run&dispatch=5885d80a13c0db1f9fecf49521b3f5afc18ba9034b1c79cbd5929eac28412d99,myemail@server.com,myrealpasswordis16characterslong,,paypal.com,,0
Also the neighboring rows don't seem to be special in any way - they certainly do not contain an overly long password.

**Comment by kspearrin** [comment]
Are you sure you are looking at the correct **row** and not the **line** number? They are different since some rows can expand multiple lines.

**Comment by NormaJeanBaker** [comment]
I looked at the error message, which in fact gives a number.
The row in question looks completely harmless to me. In fact it is this row:
https://www.paypal.com/de/cgi-bin/webscr?cmd=_login-run&dispatch=5885d80a13c0db1f9fecf49521b3f5afc18ba9034b1c79cbd5929eac28412d99,myemail@server.com,myrealpasswordis16characterslong,,paypal.com,,0
Also the neighboring rows don't seem to be special in any way - they certainly do not contain an overly long password.

**Comment by NormaJeanBaker** [comment]
Yes I am sure. All lines / rows at the beginning of the table are rather short, no line wraps anywhere.

**Comment by kspearrin** [comment]
That paypal row is definitely OK. I do not see any issues with it. I would suggest to try trimming your file down and importing it in chuncks to see if you can isolate the real problem (i.e. divide an conquer). For example, if you were to only import that paypal row (with the header), does it work?

**Comment by jeroen7s** [comment]
check if there are any wifi entries in there
lastpass seems to export that as a weird XML inside CSV layout that's completely broken
